name: elok
description: "A futuristic AI Auto Reply App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  
  # State Management & Logic
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  
  # AI & Notification
  google_generative_ai: ^0.2.0
  flutter_notification_listener: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true