dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_generative_ai: ^0.2.0
  intl: ^0.18.1
  flutter_notification_listener: ^1.1.0